// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Feb 03 10:03:30 PST 2012

package com.webmethods.caf.is.wsclient.svc.startloanprocess;

public interface IsvcPortType
  {
  public void startLoanProcess( java.lang.String LoanNumber );
  }
