// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Feb 03 10:03:30 PST 2012

package com.webmethods.caf.is.wsclient.svc.startloanprocess;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class svcServiceHelper
  {
  public static IsvcPortType bind()
    throws RegistryException
    {
    return bind( "file:/D:/Projects/bpm/mws/branches/mws_821ga/test/FormFlowProcessTasks/src/com/webmethods/caf/is/wsclient/svc/startloanprocess/startLoanProcess.wsdl" );
    }

  public static IsvcPortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IsvcPortType bind( String url , Context context )
    throws RegistryException
    {
    return (IsvcPortType) Registry.bind( url, IsvcPortType.class, context );
    }
  }
